# docker-compose.weaviate.yml
version: "3.4"
services:
  weaviate:
    image: semitechnologies/weaviate:1.24.10
    ports: ["8080:8080"]
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai"
      OPENAI_APIKEY: "${OPENAI_API_KEY}"
    volumes:
      - ./weaviate-data:/var/lib/weaviate
