global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # FastAPI backend metric collection
  - job_name: "fastapi-backend"
    static_configs:
      - targets: ["backend:8001"] # access container name within Docker network
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Weaviate metric (if enabled)
  - job_name: "weaviate"
    static_configs:
      - targets: ["weaviate:8080"]
    metrics_path: "/v1/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s
