name: Docker Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: discord-rag-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build RAG agent Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./rag_agent
          file: ./rag_agent/Dockerfile
          push: false
          tags: discord-rag-agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: discord-rag-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build bot Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bots
          file: ./bots/Dockerfile
          push: false
          tags: discord-rag-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
